# Generated by Django 4.1.7 on 2023-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=999)),
                ('author_fname', models.CharField(max_length=999)),
                ('author_lname', models.CharField(max_length=999)),
                ('release_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
