# Generated by Django 4.1.7 on 2023-03-23 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
