# Generated by Django 4.1.7 on 2023-04-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0002_book_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Beginner', 'Beginner'), ('Weight-loss', 'Weight-loss'), ('Vegetarian', 'Vegetarian'), ('Regional', 'Regional')], default='Beginner', max_length=15),
        ),
    ]
