# Generated by Django 4.1.7 on 2023-04-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0003_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Beginner', 'Beginner'), ('Weight-loss', 'Weight-loss'), ('Vegetarian', 'Vegetarian'), ('Regional', 'Regional'), ('Drinks', 'Drinks'), ('Baking', 'Baking')], default='Beginner', max_length=15),
        ),
    ]
